### ISSUE TITLE
New /me syntax causes problems and is annoying

### ISSUE THREAD

**Issue by Dico200** [RedstonerServer/redstoner-utils#15]
/me needs to be changed back. Its too visible in chat and people are spamming it. I've had to tempban a couple of players. (Including Nemes...)

**Comment by jomo** [comment]
syntax? I think you mean the output format? That can be changed in Essentials, but it's good to replace the main Essentials commands so we can finally get rid of it

**Comment by Dico200** [comment]
Oh okay I didn't search very thoroughly but /me didn't find it. And yeah I mean output format :D
