### ISSUE TITLE
/check doesn't work properly from console

### ISSUE THREAD

**Issue by Dico200** [RedstonerServer/redstoner-utils#17]
Either needs to check if sender is a player or this should be fixed. 

Output: ![pic](http://puu.sh/gHb3V/0b18655625.png)

**Comment by jomo** [comment]
This is [caused by](https://github.com/RedstonerServer/redstoner-utils/blob/dev/check.py#L76) HTTP errors - either Mojang's API is down or we're hitting their rate limit.
