### ISSUE TITLE
Add /reloadutils

### ISSUE THREAD

**Issue by Dico200** [RedstonerServer/redstoner-utils#18]
I've tried to make this work but I'm stuck.
It would be really nice to have cuz as it is now whenever we implement changes we have to reboot the server. I also have to keep restarting my test server (reloading twice causes some PermGenError and OutOfMemoryError).

So if someone knows how to reload our python plugins, I'm all ears!

I tried:
``` Python
pm = server.getPluginManager()
utilsplugin = pm.getPlugin("RedstonerUtils")
pm.disablePlugin(utilsplugin)
Event.getHandlerList().unregisterAll(pm.getPlugin("PythonLoader"))
pm.enablePlugin(utilsplugin)
```

You can't disable the python plugin because it will be unable to interprete the next lines. I tried that too. Event doesn't have getHandlerList() (it's static). If you don't unregister all events/commands (They seem to be registered to PythonLoader) it will throw a bunch of errors because all of them are already loaded when utils tries to register them.

**Comment by jomo** [comment]
This would be part of [@gdude2002/Python-Plugin-Loader](https://github.com/gdude2002/Python-Plugin-Loader) not our plugin.
