### ISSUE TITLE
blockplacemods doesn't check permission

### ISSUE THREAD

**Issue by jomo** [RedstonerServer/redstoner-utils#19]
I think you can use the right click event anywhere, you probably want to fire a block place event and check if it's cancelled before changing the block.

This is already done in the tilehelper module.

**Comment by Dico200** [comment]
I have the priority set to "monitor" and I check if the event isn't cancelled before continuing. It should be fine.

**Comment by jomo** [comment]
The problem is that a right click doesn't (necessarily) change any blocks and thus the event is not cancelled by other plugins (e.g. PlotMe).

That's why you should fire a place block event to check if a player is actually allowed to build.
