### ISSUE TITLE
/damnspam 0

### ISSUE THREAD

**Issue by ghost** [RedstonerServer/redstoner-utils#24]
So I set a button with damnspam and decided I didn't need it. I looked at it and ran "/ds 0" and it returned "The timeout must be between 0-60 or -1"

**Comment by jomo** [comment]
The only way to remove a ds lock is to destroy it (while sneaking). I see how this can be a problem in some cases.

Want to submit a PR to allow using `/ds 0` to remove the lock?

**Comment by LogalGamer** [comment]
I'll see `.`

**Comment by LogalGamer** [comment]
Here is my first attempt/half fix, haven't tested it yet so I don't wanna make a pull request until I confirm it works.
https://github.com/LogalGamer/redstoner-utils/commit/3598f0131ff2b16e0679b73d21b323d8255b2d46

**Comment by PanFritz** [comment]
First of all you have a syntax error at the comparison, should be "==" and might be smart to check if before it tries to round it

**Comment by jomo** [comment]
You can make a PR and any simply push any additonal changes to the same branch, so they'll be included in the same PR.

**Comment by LogalGamer** [comment]
Dumb question, where can I get a working version of PythonPluginLoader? The one I had messed up and the download I used is broken.

**Comment by PanFritz** [comment]
Check our wiki

**Comment by LogalGamer** [comment]
Ah thanks.

**Comment by Dico200** [comment]
I've updated damnspam to do this in my latest commit https://github.com/RedstonerServer/redstoner-utils/commit/d00301ccc3de42c6b66bf986e79ce84ca2c09d07
