### ISSUE TITLE
Yay... Another bug in setup.sh - setup.sh: 17: read: arg count

### ISSUE THREAD

**Issue by LogalGamer** [RedstonerServer/redstoner-utils#26]
Looks like read needs an argument. I changed it to `read _` and that fixed it.

**Comment by jomo** [comment]
This should be a PR, not an issue.

----

However I can't confirm your issue. The `read` builtin does not need an argument:
> If no NAMEs are supplied, the line read is stored in the REPLY variable.

Looks like it has been like that for [a long time](http://git.savannah.gnu.org/cgit/bash.git/commit/builtins/read.def?id=726f63884db0132f01745f1fb4465e6621088ccf). Are you sure you're using bash?

----

If you're on ubuntu it's possible that you have symlinked `/bin/bash` to `/bin/dash`, which is a bad idea, as you can see.
The script explicitly states that it is to be executed with `/usr/bin/env bash. If your system's `bash` is actually a bash incompatible bash-replacement, you need to fix your system :)

**Comment by LogalGamer** [comment]
Ah interesting... I haven't symlinked anything and just reinstalled on an encrypted volume yesterday. If course when updating I got some notices that my system installation was broken, so i'll check it out. :smile:
