### ISSUE TITLE
Yet another one with setup.sh... - Jar Case Error?

### ISSUE THREAD

**Issue by ghost** [RedstonerServer/redstoner-utils#27]
On line 28, your saving build tools as `buildtools.jar`
On line 31, your attempting to run `BuildTools.jar`

It's one or the other, otherwise it seems to be unable to find and load the jar.

**Comment by jomo** [comment]
This should be a PR.

**Comment by LogalGamer** [comment]
Blargh >.<

**Comment by jomo** [comment]
Will be closed automatically once the PR is merged.
PRs are for code changes + any discussion about it, issues for everything that doesn't make code changes.

**Comment by LogalGamer** [comment]
Ah ok. Still a little new to GitHub and starting to actually make these issues and pull requests.

**Comment by davidpanic** [comment]
Heh I fixed this in #30 nobody closed this tho xP
