### ISSUE TITLE
/calc doesn't block chat messages when turned on

### ISSUE THREAD

**Issue by BitByteMC** [RedstonerServer/redstoner-utils#9]
When the calculator plugin is on, it should block the messages being sent directly to chat, which is currently does not do.

**Comment by PanFritz** [comment]
It was never intended to do that, as it also calculates things inside a sentece like i just made a 3*3 door

**Comment by jomo** [comment]
> I just made a 3 * 3 door.

-
> This ram has 2^64 bits of memory
